[package]
name = "cetus-swap-sdk"
version = "0.1.0"
edition = "2021"
description = "Cetus DLMM Swap SDK"
authors = ["Cetus Technology Limited"]
license = "MIT"

[dependencies]
anyhow = "1.0"
ruint = "1.3"
serde = { version = "1.0", features = ["derive"] }
