[package]
name = "CetusDlmm"
edition = "2024"

[dependencies]
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", rev = "testnet-v1.3.0", override = true }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", rev = "testnet-v1.3.0", override = true }

[addresses]
cetusdlmm = "0xb382224d12558da5f87624765065a8c7e8f5c899d0ee890610e2bb4e8c686be9"
